"""Tests for transport-layer error handling in the client.

Regression cover for two defects:

1. client._mqtt_send referenced FranklinWHError without that class existing, so
   every sendMqtt rejection outside codes 200/102/136 raised ImportError and
   discarded the backend's actual code and message.
2. _post and _get called resp.json() unguarded and re-raised a bare
   JSONDecodeError, printing the whole body to stdout. The cloud sits behind
   CloudFront, which serves HTML error pages for 5xx — a single 504 killed a
   60-minute observation run on its second poll.
"""

import json

import pytest
from unittest.mock import AsyncMock, MagicMock

from franklinwh_cloud.exceptions import (
    DeviceTimeoutException,
    FranklinWHError,
    GatewayOfflineException,
    InvalidResponseError,
)


def _client(response):
    from franklinwh_cloud.client import Client

    c = MagicMock(spec=Client)
    c.url_base = "https://example.invalid/"
    c._post = AsyncMock(return_value=response)
    c._mqtt_send = Client._mqtt_send.__get__(c)
    return c


class TestMqttSendErrors:

    @pytest.mark.asyncio
    async def test_success_returns_response(self):
        payload = {"code": 200, "message": "Query success!", "result": {"dataArea": "{}"}}
        c = _client(payload)
        assert await c._mqtt_send("wire") is payload

    @pytest.mark.asyncio
    async def test_102_raises_device_timeout(self):
        c = _client({"code": 102, "message": "device timeout"})
        with pytest.raises(DeviceTimeoutException, match="device timeout"):
            await c._mqtt_send("wire")

    @pytest.mark.asyncio
    async def test_136_raises_gateway_offline(self):
        c = _client({"code": 136, "message": "gateway offline"})
        with pytest.raises(GatewayOfflineException, match="gateway offline"):
            await c._mqtt_send("wire")

    @pytest.mark.asyncio
    async def test_400_raises_franklinwh_error_not_import_error(self):
        """Real backend rejection observed live when the gateway id is unresolvable."""
        c = _client({"code": 400, "message": "No vpn gateway vpn!", "success": False})

        with pytest.raises(FranklinWHError) as exc:
            await c._mqtt_send("wire")

        assert exc.value.code == 400
        # The backend's own message must survive — it is the only diagnostic.
        assert "No vpn gateway vpn!" in str(exc.value)

    @pytest.mark.asyncio
    async def test_missing_code_key_does_not_raise_keyerror(self):
        """A malformed response must surface as FranklinWHError, not KeyError."""
        c = _client({"message": "malformed"})

        with pytest.raises(FranklinWHError) as exc:
            await c._mqtt_send("wire")
        assert exc.value.code is None

    @pytest.mark.asyncio
    async def test_error_is_catchable_as_exception(self):
        """Must derive from Exception, not BaseException — callers use `except Exception`."""
        assert issubclass(FranklinWHError, Exception)
        c = _client({"code": 500, "message": "boom"})
        try:
            await c._mqtt_send("wire")
        except Exception as e:
            assert isinstance(e, FranklinWHError)
        else:
            pytest.fail("expected FranklinWHError")


# ── Non-JSON response decoding ───────────────────────────────────────

# The exact body CloudFront returned when the 60-minute observation died.
CLOUDFRONT_504 = (
    '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">\n'
    '<HTML><HEAD><TITLE>ERROR: The request could not be satisfied</TITLE></HEAD>\n'
    '<BODY><H1>504 Gateway Timeout ERROR</H1>\n'
    '<H2>The request could not be satisfied.</H2>\n'
    'Generated by cloudfront (CloudFront) HTTP3 Server\n</BODY></HTML>'
)


def _resp(text, status=200):
    r = MagicMock()
    r.text = text
    r.status_code = status
    r.json.side_effect = lambda: json.loads(text)
    return r


class TestDecodeJson:

    def test_valid_json_passes_through(self):
        from franklinwh_cloud.client import Client
        out = Client._decode_json(_resp('{"code": 200}'), "GET", "https://x/y")
        assert out == {"code": 200}

    def test_empty_body_is_treated_as_success(self):
        """Some endpoints answer 200 with no body — that is success, not an error."""
        from franklinwh_cloud.client import Client
        out = Client._decode_json(_resp("   "), "POST", "https://x/y")
        assert out["code"] == 200 and out["result"]["dataArea"] == "{}"

    def test_cloudfront_504_raises_typed_error_not_jsondecodeerror(self):
        from franklinwh_cloud.client import Client

        with pytest.raises(InvalidResponseError) as exc:
            Client._decode_json(_resp(CLOUDFRONT_504, status=504), "GET", "https://x/y")

        assert exc.value.status_code == 504
        assert "504" in str(exc.value)

    def test_is_catchable_as_franklinwh_error(self):
        """Long-running pollers guard with `except FranklinWHError` — a CDN blip
        must be covered by that guard without knowing about HTTP internals."""
        from franklinwh_cloud.client import Client

        with pytest.raises(FranklinWHError):
            Client._decode_json(_resp(CLOUDFRONT_504, status=504), "GET", "https://x/y")

    def test_body_is_truncated_not_dumped_whole(self):
        from franklinwh_cloud.client import Client

        with pytest.raises(InvalidResponseError) as exc:
            Client._decode_json(_resp("x" * 5000, status=502), "GET", "https://x/y")

        assert len(exc.value.body) == 500

    def test_original_decode_error_is_chained(self):
        from franklinwh_cloud.client import Client

        with pytest.raises(InvalidResponseError) as exc:
            Client._decode_json(_resp("not json", status=200), "GET", "https://x/y")

        assert isinstance(exc.value.__cause__, json.JSONDecodeError)
